// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhhzdykyjgrnprcyhlbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaHpkeWt5amdybnByY3lobGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTI0MzUsImV4cCI6MjA2NDEyODQzNX0.1PIDZh1V88rPEfBUQYcndYSYiGuPoNaD4HRFaABH-Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);